import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Youtube, 
  Search, 
  FileText as FileIcon, 
  Download, 
  Loader2, 
  AlertCircle,
  Play,
  List,
  Image as ImageIcon,
  Mic,
  Video as VideoIcon,
  MessageSquare,
  Check
} from 'lucide-react';
import { ExtractionResult, VideoDetails, PlaylistDetails } from './types';

export default function App() {
  const [url, setUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ExtractionResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleExtract = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!url) return;

    setLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch('/api/extract', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to extract content');
      }

      const data = await response.json();
      setResult(data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const generateMarkdown = (data: ExtractionResult) => {
    let md = '';
    if (data.type === 'video') {
      md = `# YouTube Content: ${data.title}\n\n`;
      md += `**Author:** ${data.author}\n`;
      md += `**URL:** ${data.videoUrl}\n`;
      md += `**Published:** ${data.publishDate}\n`;
      md += `**Duration:** ${Math.floor(data.duration / 60)}m ${data.duration % 60}s\n\n`;
      
      md += `## Description\n${data.description}\n\n`;
      
      md += `## Visuals & Screenshots\n`;
      md += `![Main Thumbnail](${data.thumbnail})\n\n`;
      
      md += `## Transcript / Subtitles\n${data.transcript}\n\n`;
      
      md += `--- \n*Generated by YT Content Forge*`;
    } else {
      md = `# YouTube Playlist: ${data.title}\n\n`;
      md += `**Author:** ${data.author}\n`;
      md += `**Video Count:** ${data.videoCount}\n\n`;
      
      md += `## Videos\n`;
      data.videos.forEach((v, i) => {
        md += `### ${i + 1}. ${v.title}\n`;
        md += `- **URL:** ${v.url}\n`;
        md += `- **Duration:** ${v.duration}\n`;
        md += `![Thumbnail](${v.thumbnail})\n\n`;
      });
      
      md += `--- \n*Generated by YT Content Forge*`;
    }

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `youtube-content-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full h-screen flex flex-col overflow-hidden text-slate-200 border border-slate-800 shadow-2xl relative bg-slate-950 font-sans">
      {/* Header */}
      <header className="h-16 flex items-center justify-between px-8 border-b border-slate-800 glass z-10 shrink-0">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-brand-primary rounded-lg flex items-center justify-center text-white">
            <Youtube className="w-5 h-5" />
          </div>
          <h1 className="text-xl font-bold tracking-tight text-white font-sans">
            TubeScraper <span className="text-brand-primary">Pro</span>
          </h1>
        </div>
        <div className="flex gap-4 items-center">
          <div className="text-xs font-semibold px-3 py-1 rounded-full bg-slate-800 text-slate-400 border border-slate-700 font-mono">
            v1.0.0 Stable
          </div>
          <div className="w-8 h-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center">
            <div className={`w-2 h-2 rounded-full ${loading ? 'bg-amber-400 animate-pulse' : 'bg-emerald-400'}`}></div>
          </div>
        </div>
      </header>

      <main className="flex-1 flex overflow-hidden">
        {/* Sidebar */}
        <aside className="w-80 border-r border-slate-800 p-6 flex flex-col gap-6 glass bg-slate-900/50 shrink-0">
          <section>
            <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-2 font-mono">Source Link</label>
            <textarea 
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              className="w-full h-24 bg-slate-950 border border-slate-700 rounded-lg p-3 text-sm text-slate-300 focus:outline-none focus:ring-1 focus:ring-brand-primary/50 placeholder-slate-600 resize-none font-sans" 
              placeholder="Paste Video or Playlist URL..."
            />
          </section>

          <section>
            <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-3 font-mono">Extraction Assets</label>
            <div className="space-y-1">
              {[
                { label: 'Video Meta', icon: VideoIcon, checked: true },
                { label: 'Audio Details', icon: Mic, checked: true },
                { label: 'Transcripts (CC)', icon: MessageSquare, checked: true },
                { label: 'Key Visuals', icon: ImageIcon, checked: true },
              ].map((item, idx) => (
                <div key={idx} className="flex items-center justify-between p-2 rounded hover:bg-slate-800/50 transition-colors">
                  <div className="flex items-center gap-2">
                    <item.icon className="w-4 h-4 text-slate-500" />
                    <span className="text-sm">{item.label}</span>
                  </div>
                  <div className={`w-4 h-4 rounded border ${item.checked ? 'bg-brand-primary border-brand-primary' : 'border-slate-700'}`}>
                    {item.checked && <Check className="w-4 h-4 text-white" />}
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="mt-auto">
            <button 
              onClick={() => handleExtract()}
              disabled={loading || !url}
              className="w-full py-3 bg-brand-primary hover:bg-brand-secondary text-white font-bold rounded-lg transition-all shadow-lg shadow-brand-primary/20 active:scale-[0.98] flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed uppercase text-sm tracking-wide"
            >
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Search className="w-4 h-4" />}
              FETCH_CONTENT
            </button>
            {result && (
              <button 
                onClick={() => generateMarkdown(result)}
                className="w-full mt-3 py-3 bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold rounded-lg transition-all border border-slate-700 flex items-center justify-center gap-2 uppercase text-xs tracking-widest"
              >
                <Download className="w-4 h-4" />
                GENERATE_MD
              </button>
            )}
          </section>

          {error && (
            <div className="p-3 bg-brand-primary/10 border border-brand-primary/20 rounded-lg flex items-center gap-2 text-brand-primary text-xs font-mono">
              <AlertCircle className="w-4 h-4 shrink-0" />
              {error}
            </div>
          )}
        </aside>

        {/* Console / Output Area */}
        <section className="flex-1 flex flex-col bg-slate-950 p-6 overflow-hidden">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <FileIcon className="w-4 h-4 text-slate-500" />
              <span className="text-sm font-medium text-slate-400 font-mono italic">
                {result ? `${result.type === 'video' ? 'video' : 'playlist'}_view.md` : 'awaiting_input.md'}
              </span>
            </div>
          </div>

          <div className="flex-1 bg-slate-900 border border-slate-800 rounded-xl overflow-hidden flex flex-col shadow-inner">
            <div className="h-10 bg-slate-800/50 flex items-center px-4 border-b border-slate-800 shrink-0">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-slate-700"></div>
                <div className="w-3 h-3 rounded-full bg-slate-700"></div>
                <div className="w-3 h-3 rounded-full bg-slate-700"></div>
              </div>
            </div>
            
            <div className="flex-1 p-6 overflow-y-auto font-mono text-sm custom-scrollbar text-slate-300 leading-relaxed">
              <AnimatePresence mode="wait">
                {result ? (
                  <motion.div
                    key="active-result"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                  >
                    {result.type === 'video' ? (
                      <div className="space-y-4">
                        <h2 className="text-blue-400 text-lg font-bold"># YouTube Content: {result.title}</h2>
                        <div className="space-y-1">
                          <p><span className="text-emerald-400 font-bold">- Author:</span> {result.author}</p>
                          <p><span className="text-emerald-400 font-bold">- Published:</span> {result.publishDate}</p>
                          <p><span className="text-emerald-400 font-bold">- Duration:</span> {Math.floor(result.duration / 60)}m {result.duration % 60}s</p>
                        </div>
                        
                        <h3 className="text-slate-500 font-bold mt-6">## Visuals Captured</h3>
                        <div className="grid grid-cols-2 gap-4 my-4">
                           <div className="aspect-video rounded border border-slate-700 overflow-hidden bg-slate-800">
                              <img src={result.thumbnail} alt="" className="w-full h-full object-cover" />
                           </div>
                           <div className="grid grid-cols-2 gap-2">
                             {result.visuals.slice(0, 4).map((v, i) => (
                               <div key={i} className="aspect-video rounded border border-slate-700 overflow-hidden bg-slate-800">
                                  <img src={v} alt="" className="w-full h-full object-cover" />
                               </div>
                             ))}
                           </div>
                        </div>

                        <h3 className="text-slate-500 font-bold mt-6">## Transcript</h3>
                        <div className="bg-slate-950 p-4 rounded border border-slate-800 text-slate-400 italic">
                          {result.transcript}
                        </div>

                        <h3 className="text-slate-500 font-bold mt-6">## Description</h3>
                        <div className="text-slate-500 whitespace-pre-wrap">{result.description}</div>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        <h2 className="text-blue-400 text-lg font-bold"># Playlist: {result.title}</h2>
                        <p><span className="text-emerald-400 font-bold">- Videos Found:</span> {result.videoCount}</p>
                        
                        <div className="space-y-6 mt-6">
                          {result.videos.map((v, i) => (
                            <div key={v.id} className="border-l-2 border-slate-800 pl-4 space-y-2">
                              <h4 className="text-orange-400 font-bold">Video {i + 1}: {v.title}</h4>
                              <p className="text-xs text-slate-500 uppercase">{v.duration} min • {v.url}</p>
                              <div className="w-48 aspect-video rounded-md border border-slate-800 overflow-hidden mt-2">
                                <img src={v.thumbnail} alt="" className="w-full h-full object-cover" />
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </motion.div>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center opacity-30 select-none">
                    <Youtube className="w-16 h-16 mb-4" />
                    <p className="text-xs tracking-[0.2em] font-bold uppercase">Ready for Stream Input</p>
                    <p className="text-[10px] mt-2 opacity-50 font-mono">./sys/awaiting_target_url</p>
                  </div>
                )}
              </AnimatePresence>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="h-12 border-t border-slate-800 flex items-center justify-between px-6 bg-slate-900 text-[10px] uppercase tracking-widest text-slate-500 shrink-0">
        <div className="flex items-center gap-2">
          Status: <span className={loading ? 'text-amber-500' : 'text-emerald-500'}>{loading ? 'Extracting...' : 'System Ready'}</span>
        </div>
        <div>YT.FORGE Session: {Date.now().toString().slice(-8)}</div>
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1"><div className="w-1.5 h-1.5 rounded-full bg-emerald-500"></div> Auth Link Valid</span>
          <span>Storage: 1.2GB / 5.0GB</span>
        </div>
      </footer>
    </div>
  );
}
